### ISSUE TITLE
Onboard->I selected yes for launcher installation,but launcher not installed

### ISSUE THREAD

**Issue by Mercypaul27** [wployalty/wll-loyalty-launcher#11]
[Screencast from 26-12-24 02:22:52 PM IST.webm](https://github.com/user-attachments/assets/1370a6fd-530a-4cf9-84fe-282adde8f369)

**Comment by sabhari-krr** [comment]
Fixed.

Note: The icon might not be visible, because, the stable release was downloaded, and in the stable release, the icon URL is wrong. Please don't consider that as an issue. It will be fixed in the upcoming release.

[Screencast from 2024-12-26 20-28-18.webm](https://github.com/user-attachments/assets/9c4c2f86-07a0-4175-8d40-aff9b25f4de4)

**Comment by Mercypaul27** [comment]
Fixed
![image](https://github.com/user-attachments/assets/d395c61f-6227-44f2-98cb-e50818c46a66)
